### ISSUE TITLE
Cannot read properties of undefined (reading 'route')

### ISSUE THREAD

**Issue by elvinn** [vercel/speed-insights#34] opened 2023-12-22 03:14 UTC
According to [Doc - Speed Insights
](https://vercel.com/elvinns-projects/the-faintest-ink/speed-insights?period=24h&environment=production&device=mobile&metric=RES)，I should use `injectSpeedInsights();` to init in *other framework*.

<img width="859" alt="image" src="https://github.com/vercel/speed-insights/assets/28722527/4fd15259-6813-480a-a921-7172560b1a65">

However, it will throw an error like below:

<img width="1144" alt="image" src="https://github.com/vercel/speed-insights/assets/28722527/e007a3f2-a8d7-43ec-baad-a3adc2b03656">
<img width="726" alt="image" src="https://github.com/vercel/speed-insights/assets/28722527/cd3b3485-8d54-4285-a610-35212880a946">

Solution: should I use `injectSpeedInsights({});` instead of `injectSpeedInsights();` ? In the source code, `props` is not optional, otherwise it will throw an error when execute `props.router`.

**Comment by feugy** [comment] 2024-01-12 08:26
Hello @elvinn , thank you for the but report.
This is a duplicate of #32, let's continue the discussion there.

**Closed by feugy** 2024-01-12 08:26 UTC
